Add missing include for writev
nat64.c:119:6: warning: implicit declaration of function `writev'; did you mean `write'? [-Wimplicit-function-declaration]
  if (writev(gcfg->tun_fd, iov, data_len ? 2 : 1) < 0)
      ^~~~~~
      write

Gbp-Pq: Name 0010-include-for-writev.patch